import React, { type ReactNode } from "react";
import { Bell, House, Menu, MessageCircle, Plus, Search, UserRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { BrandLogo } from "@/components/branding/BrandLogo";
import { ThemeToggle } from "@/components/shared/ThemeToggle";
const links = [{ label: "الرئيسية", href: "/", icon: House }, { label: "استكشف", href: "/explore", icon: Search }, { label: "نشر مهمة", href: "/employer", icon: Plus, raised: true }, { label: "الرسائل", href: "/messages", icon: MessageCircle }, { label: "حسابي", href: "/profile", icon: UserRound }];
export function PhaseBottomNavigation({ activePath }: { activePath: string }) { return <nav className="phase-bottom-nav" aria-label="التنقل الرئيسي">{links.map(({ label, href, icon: Icon, raised }) => <Link key={href} href={href} className={`${activePath === href ? "is-active" : ""} ${raised ? "is-raised" : ""}`}><span>{raised ? <span className="nav-plus"><Plus size={21} /></span> : <Icon size={20} />}</span><small>{label}</small></Link>)}</nav>; }
export function AppShell({ children }: { children: ReactNode }) { const [location] = useLocation(); return <div className="phase-app-shell"><header className="phase-header"><Link href="/" className="phase-brand"><BrandLogo /></Link><nav className="phase-desktop-nav" aria-label="التنقل الرئيسي">{links.slice(0, 2).map(item => <Link key={item.href} href={item.href} className={location === item.href ? "is-active" : ""}>{item.label}</Link>)}<Link href="/employer">نشر مهمة</Link></nav><div className="phase-header-actions"><button type="button" aria-label="بحث" onClick={() => { location === "/explore" ? toast.info("اكتب في حقل البحث لاستعراض فرص الواجهة") : window.location.assign("/explore"); }}><Search size={19} /></button><button type="button" aria-label="إشعارات" onClick={() => toast.info("لا توجد إشعارات جديدة حالياً")}><Bell size={19} /><i /></button><ThemeToggle /><button className="header-menu" type="button" aria-label="فتح القائمة" onClick={() => toast.info("سيتم توسيع القائمة في مرحلة لاحقة")}><Menu size={20} /></button></div></header><main className="phase-main">{children}</main><PhaseBottomNavigation activePath={location} /></div>; }
export function PageHeading({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <p>{eyebrow}</p>}<h1>{title}</h1></div>{action}</div>; }
