import React, { useState } from "react";
import { motion } from "framer-motion";
import { Bookmark, Clock3, Heart, MapPin, Wallet } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import type { Job } from "@/lib/phase3-data";
import { StatusBadge } from "./StatusBadge";
export function PhaseJobCard({ job, compact = false }: { job: Job; compact?: boolean }) { const [saved, setSaved] = useState(false); const save = () => { setSaved(value => !value); toast.success(saved ? "أزلنا المهمة من المحفوظات" : "حُفظت المهمة في حسابك"); }; return <motion.article className={`phase-job-card ${compact ? "phase-job-card-compact" : ""}`} whileHover={{ y: -4 }} whileTap={{ scale: .985 }} transition={{ duration: .22 }}><span className="notice-crescent" aria-hidden="true">◔</span><div className="job-card-top"><div className="employer-mark" aria-hidden="true">{job.initials}</div><div className="job-title-wrap"><div className="job-label-row"><span className="category-pill">{job.category}</span>{job.urgent && <StatusBadge type="urgent" />}</div><h3>{job.title}</h3><p>{job.employer}{job.verified && <span className="verified-dot" title="جهة موثقة" />}</p></div><button className={`save-job ${saved ? "is-saved" : ""}`} type="button" onClick={save} aria-label={saved ? "إزالة من المحفوظات" : "حفظ المهمة"} aria-pressed={saved}>{saved ? <Bookmark size={19} fill="currentColor" /> : <Heart size={19} />}</button></div><div className="job-metrics"><span><Wallet size={15} /> <b>{job.payment}</b></span><span><Clock3 size={15} /> {job.duration}</span><span><MapPin size={15} /> {job.distance}</span></div>{!compact && <div className="job-card-actions"><Link href={`/jobs/${job.id}`} className="job-details-link">عرض التفاصيل</Link><button type="button" className="mini-apply" onClick={() => toast.info("سيصبح التقديم متاحاً عند ربط تدفق الطلبات")}>قدّم الآن</button></div>}</motion.article>; }
export function JobCardSkeleton() { return <article className="phase-job-card job-skeleton" aria-label="جارٍ تحميل الفرصة"><div className="skeleton skeleton-avatar" /><div className="skeleton-stack"><div className="skeleton skeleton-line long" /><div className="skeleton skeleton-line short" /><div className="skeleton skeleton-line medium" /></div></article>; }
