import { useState } from "react";
import { Link, useLocation } from "wouter";
import { AuthFeedback, AuthFrame } from "./AuthFrame";
import { registerWithEmail } from "@/lib/api/auth";

export default function Register() {
  const [, setLocation] = useLocation(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string>(); const [accepted, setAccepted] = useState(false); const [legalOpen, setLegalOpen] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!accepted) { setLegalOpen(true); return; } const form = new FormData(event.currentTarget); setLoading(true); setMessage(undefined); const result = await registerWithEmail({ fullName: String(form.get("fullName") ?? ""), email: String(form.get("email") ?? ""), password: String(form.get("password") ?? ""), role: String(form.get("role") ?? "job_seeker") as "job_seeker" | "employer" }); setLoading(false); if (result.success) { setMessage(result.message); event.currentTarget.reset(); } else setMessage(result.message); };
  return <AuthFrame title="أنشئ حسابك" description="ابدأ بخطوات بسيطة، ثم اختر الفرصة الأنسب لوقتك."><form className="auth-form" onSubmit={submit}><label>الاسم الكامل<input name="fullName" autoComplete="name" required minLength={2} maxLength={120} placeholder="مثال: سلمى بنعلي" /></label><label>البريد الإلكتروني<input name="email" type="email" autoComplete="email" required placeholder="name@example.com" /></label><label>كلمة المرور<input name="password" type="password" autoComplete="new-password" required minLength={8} placeholder="٨ أحرف على الأقل" /></label><label>أنت تسجّل كـ<select name="role" defaultValue="job_seeker"><option value="job_seeker">باحث عن فرصة</option><option value="employer">صاحب عمل</option></select></label><button type="button" className={`consent-card ${accepted ? "consent-card-accepted" : ""}`} onClick={() => setLegalOpen(true)}><span className="consent-check">{accepted ? "✓" : ""}</span><span><b>{accepted ? "تم قبول إخلاء المسؤولية" : "اقرأ ووافق على إخلاء المسؤولية"}</b><small>مطلوب قبل إنشاء الحساب</small></span></button><AuthFeedback message={message} tone={message?.includes("تحقق") ? "success" : "error"} /><button className="primary-cta auth-submit" disabled={loading}>{loading ? "جارٍ إنشاء الحساب…" : "إنشاء الحساب"}</button></form><p className="auth-footnote">لديك حساب؟ <Link href="/login">سجّل الدخول</Link></p>{legalOpen && <div className="legal-overlay" role="dialog" aria-modal="true" aria-labelledby="legal-title"><div className="legal-modal"><p className="eyebrow"><span className="brand-marker" aria-hidden="true"><i /></span> موافقة مطلوبة</p><h2 id="legal-title">إخلاء مسؤولية المنصة</h2><p>بريكولي منصة تقنية تسهّل التعارف بين أصحاب الأعمال المحليين والباحثين عن فرص قصيرة. لا تكون بريكولي طرفاً في علاقة العمل أو في الاتفاق المالي أو في تنفيذ المهمة.</p><p>أتعهد بتقديم معلومات صحيحة، وباستخدام المنصة باحترام وأمان، وبفهم أن أي اتفاق يتم مباشرة بين الأطراف المعنية.</p><div className="legal-actions"><button type="button" className="secondary-cta" onClick={() => setLegalOpen(false)}>إلغاء</button><button type="button" className="primary-cta" onClick={() => { setAccepted(true); setLegalOpen(false); setMessage(undefined); }}>أوافق وأتابع</button></div></div></div>}</AuthFrame>;
}
