import React, { useRef, useState } from "react";
import { ImagePlus, Mic, Pause, Play, Send, Square, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Props = { conversationId: string; disabled: boolean; onSent: () => void; onTypingChange?: (typing: boolean) => void };
const readDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });
const ext = (mime: string) => ({ "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "image/avif": "avif", "audio/webm": "webm", "audio/ogg": "ogg", "audio/mpeg": "mp3", "audio/wav": "wav" }[mime] ?? "bin");

export function ChatComposer({ conversationId, disabled, onSent, onTypingChange }: Props) { const [text, setText] = useState(""); const [image, setImage] = useState<{ file: File; url: string } | null>(null); const [recording, setRecording] = useState(false); const [paused, setPaused] = useState(false); const [voice, setVoice] = useState<{ blob: Blob; url: string; durationMs: number } | null>(null); const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const started = useRef(0); const timer = useRef<number | null>(null); const typingTimer = useRef<number | null>(null); const sendText = trpc.brikouli.messaging.sendText.useMutation({ onSuccess: result => { if (!result.success) return toast.error(result.message); setText(""); onTypingChange?.(false); onSent(); }, onError: () => toast.error("تعذر إرسال الرسالة.") }); const sendMedia = trpc.brikouli.messaging.sendMedia.useMutation({ onSuccess: result => { if (!result.success) return toast.error(result.message); clearImage(); clearVoice(); onSent(); }, onError: () => toast.error("تعذر إرسال المرفق.") });
  const busy = sendText.isPending || sendMedia.isPending;
  const clearImage = () => { if (image) URL.revokeObjectURL(image.url); setImage(null); };
  const clearVoice = () => { if (voice) URL.revokeObjectURL(voice.url); setVoice(null); };
  const send = () => { const value = text.trim(); if (!value || busy || disabled) return; sendText.mutate({ conversationId, content: value }); };
  const chooseImage = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!["image/jpeg", "image/png", "image/webp", "image/avif"].includes(file.type) || file.size > 8 * 1024 * 1024) return toast.error("اختر صورة JPEG أو PNG أو WebP أو AVIF بحجم لا يتجاوز 8 ميغابايت."); clearImage(); setImage({ file, url: URL.createObjectURL(file) }); };
  const uploadImage = async () => { if (!image || disabled || busy) return; try { sendMedia.mutate({ conversationId, dataUrl: await readDataUrl(image.file), mimeType: image.file.type as "image/jpeg" | "image/png" | "image/webp" | "image/avif", fileName: image.file.name || `image.${ext(image.file.type)}`, durationMs: null }); } catch { toast.error("تعذر تجهيز الصورة."); } };
  const stopRecorder = (save = true) => { if (!recorder.current) return; recorder.current.onstop = () => { stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; if (timer.current) window.clearTimeout(timer.current); const blob = new Blob(chunks.current, { type: recorder.current?.mimeType || "audio/webm" }); if (save && blob.size) { clearVoice(); setVoice({ blob, url: URL.createObjectURL(blob), durationMs: Math.min(30_000, Date.now() - started.current) }); } recorder.current = null; chunks.current = []; setRecording(false); setPaused(false); }; recorder.current.stop(); };
  const startRecorder = async () => { if (disabled || busy || !navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") return toast.error("التسجيل الصوتي غير مدعوم في هذا المتصفح."); try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); const preferred = ["audio/webm;codecs=opus", "audio/ogg;codecs=opus", "audio/webm"].find(MediaRecorder.isTypeSupported); const active = new MediaRecorder(stream.current, preferred ? { mimeType: preferred } : undefined); chunks.current = []; active.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data); }; recorder.current = active; started.current = Date.now(); active.start(); setRecording(true); timer.current = window.setTimeout(() => stopRecorder(true), 30_000); } catch { toast.error("اسمح بالوصول إلى الميكروفون لتسجيل رسالة صوتية."); } };
  const togglePause = () => { if (!recorder.current) return; if (recorder.current.state === "recording") { recorder.current.pause(); setPaused(true); } else if (recorder.current.state === "paused") { recorder.current.resume(); setPaused(false); } };
  const uploadVoice = async () => { if (!voice || disabled || busy) return; try { const file = new File([voice.blob], `voice-${Date.now()}.${ext(voice.blob.type || "audio/webm")}`, { type: voice.blob.type || "audio/webm" }); sendMedia.mutate({ conversationId, dataUrl: await readDataUrl(file), mimeType: file.type as "audio/webm" | "audio/ogg" | "audio/mpeg" | "audio/wav", fileName: file.name, durationMs: voice.durationMs }); } catch { toast.error("تعذر تجهيز التسجيل الصوتي."); } };
  if (disabled) return <div className="chat-closed-composer">هذه المحادثة مغلقة للقراءة فقط.</div>;
  return <section className="chat-composer" aria-label="كتابة رسالة"><input className="sr-only" id="chat-image-input" type="file" accept="image/jpeg,image/png,image/webp,image/avif" capture="environment" onChange={chooseImage}/>{image && <div className="chat-media-preview"><img src={image.url} alt="معاينة الصورة قبل الإرسال"/><div><b>{image.file.name}</b><small>{Math.ceil(image.file.size / 1024)} كيلوبايت</small></div><button type="button" aria-label="إلغاء الصورة" onClick={clearImage}><X size={17}/></button><button type="button" className="chat-preview-send" onClick={() => void uploadImage()} disabled={busy}>إرسال الصورة</button></div>}{voice && <div className="chat-media-preview chat-voice-preview"><button type="button" className="chat-audio-play" aria-label="تشغيل المعاينة" onClick={event => { const audio = event.currentTarget.nextElementSibling as HTMLAudioElement; audio.paused ? void audio.play() : audio.pause(); }}><Play size={17}/></button><audio src={voice.url}/><div><b>رسالة صوتية جاهزة</b><small>{Math.ceil(voice.durationMs / 1000)} ثانية</small></div><button type="button" aria-label="إلغاء التسجيل" onClick={clearVoice}><Trash2 size={17}/></button><button type="button" className="chat-preview-send" onClick={() => void uploadVoice()} disabled={busy}>إرسال التسجيل</button></div>}{recording ? <div className="chat-recording-bar"><span className="chat-recording-dot"/><b>{paused ? "التسجيل متوقف مؤقتاً" : "جارٍ التسجيل — 30 ثانية كحد أقصى"}</b><button type="button" aria-label={paused ? "استئناف التسجيل" : "إيقاف التسجيل مؤقتاً"} onClick={togglePause}>{paused ? <Mic size={17}/> : <Pause size={17}/>}</button><button type="button" aria-label="إنهاء التسجيل" onClick={() => stopRecorder(true)}><Square size={15}/></button><button type="button" aria-label="إلغاء التسجيل" onClick={() => stopRecorder(false)}><Trash2 size={17}/></button></div> : <div className="chat-composer-row"><label htmlFor="chat-image-input" className="chat-composer-icon" aria-label="إضافة صورة"><ImagePlus size={21}/></label><textarea value={text} onChange={event => { const value = event.target.value; setText(value); onTypingChange?.(Boolean(value.trim())); if (typingTimer.current) window.clearTimeout(typingTimer.current); if (value.trim()) typingTimer.current = window.setTimeout(() => onTypingChange?.(false), 1400); }} onBlur={() => onTypingChange?.(false)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }} placeholder="اكتب رسالة…" rows={1} maxLength={4000}/><button type="button" className="chat-composer-icon" aria-label="تسجيل رسالة صوتية" onClick={() => void startRecorder()}><Mic size={21}/></button><button type="button" className="chat-send-button" aria-label="إرسال الرسالة" onClick={send} disabled={!text.trim() || busy}><Send size={19}/></button></div>}</section>; }
