import { useEffect, useRef } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Refresh = () => void;
type TypingState = { userId: string; typing: boolean; updatedAt: string };

export function useInboxRealtime(enabled: boolean, onRefresh: Refresh) { const latest = useRef(onRefresh); latest.current = onRefresh; useEffect(() => { if (!enabled) return; const client = getSupabaseBrowserClient(); const channel = client.channel("brikouli:inbox").on("postgres_changes", { event: "*", schema: "public", table: "conversations" }, () => latest.current()).on("postgres_changes", { event: "*", schema: "public", table: "conversation_members" }, () => latest.current()).on("postgres_changes", { event: "*", schema: "public", table: "messages" }, () => latest.current()).subscribe(); return () => { void client.removeChannel(channel); }; }, [enabled]); }

export function useConversationRealtime({ conversationId, userId, enabled, onRefresh, onTyping }: { conversationId: string; userId: string; enabled: boolean; onRefresh: Refresh; onTyping: (typing: boolean) => void }) { const refresh = useRef(onRefresh); const typingCallback = useRef(onTyping); refresh.current = onRefresh; typingCallback.current = onTyping; const presenceRef = useRef<ReturnType<ReturnType<typeof getSupabaseBrowserClient>["channel"]> | null>(null); useEffect(() => { if (!enabled || !conversationId || !userId) return; const client = getSupabaseBrowserClient(); const changes = client.channel(`brikouli:messages:${conversationId}`).on("postgres_changes", { event: "*", schema: "public", table: "messages", filter: `conversation_id=eq.${conversationId}` }, () => refresh.current()).on("postgres_changes", { event: "UPDATE", schema: "public", table: "conversations", filter: `id=eq.${conversationId}` }, () => refresh.current()).subscribe(); const presence = client.channel(`conversation:${conversationId}`, { config: { private: true, presence: { key: userId } } }).on("presence", { event: "sync" }, () => { const all = Object.values(presence.presenceState<TypingState>()).flat(); typingCallback.current(all.some(state => state.userId !== userId && state.typing)); }).subscribe(status => { if (status === "SUBSCRIBED") void presence.track({ userId, typing: false, updatedAt: new Date().toISOString() }); }); presenceRef.current = presence; return () => { void presence.untrack(); void client.removeChannel(changes); void client.removeChannel(presence); presenceRef.current = null; typingCallback.current(false); }; }, [conversationId, enabled, userId]); return { setTyping: (typing: boolean) => { const channel = presenceRef.current; if (channel) void channel.track({ userId, typing, updatedAt: new Date().toISOString() }); } }; }
