import { z } from "zod";

export const profileSchema = z.object({ fullName: z.string().trim().min(2).max(120), phone: z.string().trim().regex(/^\+[1-9]\d{7,31}$/).optional().nullable(), city: z.string().trim().max(120).optional().nullable(), neighborhood: z.string().trim().max(120).optional().nullable(), avatarUrl: z.string().url().max(2048).optional().nullable() });
export const gigSchema = z.object({ title: z.string().trim().min(4).max(140), description: z.string().trim().min(12).max(4000), category: z.string().trim().min(2).max(80), city: z.string().trim().min(2).max(120), neighborhood: z.string().trim().max(120).optional().nullable(), latitude: z.number().min(-90).max(90).optional().nullable(), longitude: z.number().min(-180).max(180).optional().nullable(), payment: z.number().positive().max(99999999), paymentType: z.enum(["fixed", "hourly"]), duration: z.string().trim().min(1).max(80) });
export const applicationSchema = z.object({ gigId: z.string().uuid() });
export const savedGigSchema = z.object({ gigId: z.string().uuid() });
export const applicationListSchema = z.object({ status: z.enum(["pending", "accepted", "rejected"]).optional() });
export const jobSeekerGigQuerySchema = z.object({ query: z.string().trim().max(120).optional().default(""), category: z.string().trim().min(2).max(80).optional(), urgentOnly: z.boolean().default(false), sort: z.enum(["newest", "highest_pay"]).default("newest"), limit: z.number().int().min(1).max(80).default(40) });
export const nearbyGigQuerySchema = z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), radiusKm: z.union([z.literal(1), z.literal(3), z.literal(5), z.literal(10)]).default(5), sort: z.enum(["distance", "newest", "highest_pay"]).default("distance"), category: z.string().trim().min(2).max(80).optional(), urgentOnly: z.boolean().default(false), minPayment: z.number().nonnegative().optional(), maxPayment: z.number().positive().optional(), limit: z.number().int().min(1).max(100).default(50) }).refine(value => value.maxPayment === undefined || value.minPayment === undefined || value.maxPayment >= value.minPayment, { message: "الحد الأعلى للمقابل يجب أن يكون أكبر من الحد الأدنى." });
export const locationSearchSchema = z.object({ query: z.string().trim().min(2, "اكتب حرفين على الأقل للبحث.").max(120) });
export const employerCategoryValues = ["متجر", "مطعم", "تنظيم", "استقبال", "تنظيف", "توصيل", "أخرى"] as const;
export const employerGigStatusValues = ["draft", "active", "assigned", "completed", "cancelled"] as const;

const hazardousGigPattern = /(high[ -]?voltage|live[ -]?wire|heavy[ -]?construction|high[ -]?altitude|كهرباء\s+جهد\s+عال|أسلاك\s+مكشوفة|بناء\s+ثقيل|ارتفاع\s+عال)/i;
export function hazardousGigWarning(input: Pick<{ title: string; description: string; category: string }, "title" | "description" | "category">) { return hazardousGigPattern.test(`${input.title} ${input.description} ${input.category}`) ? "لا يمكن نشر أعمال كهرباء الجهد العالي أو البناء الثقيل أو الصيانة في الارتفاعات حفاظاً على السلامة." : null; }
const employerGigFields = z.object({ title: z.string().trim().min(4, "اكتب عنواناً أوضح للفرصة.").max(140), description: z.string().trim().min(12, "أضف وصفاً كافياً للفرصة.").max(4000), category: z.enum(employerCategoryValues), city: z.string().trim().min(2).max(120), neighborhood: z.string().trim().max(120).optional().nullable(), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable(), payment: z.number().positive().max(99999999), paymentType: z.enum(["fixed", "hourly"]), duration: z.string().trim().min(1).max(80), workDate: z.string().date().optional().nullable(), acceptanceLimit: z.number().int().min(1).max(20).default(1) });
export const employerGigCreateSchema = employerGigFields.extend({ publish: z.boolean().default(false) }).superRefine((value, ctx) => { const warning = hazardousGigWarning(value); if (warning) ctx.addIssue({ code: z.ZodIssueCode.custom, message: warning, path: ["title"] }); });
export const employerGigUpdateSchema = employerGigFields.partial().extend({ gigId: z.string().uuid(), publish: z.boolean().optional() }).superRefine((value, ctx) => { if (value.title && value.description && value.category) { const warning = hazardousGigWarning({ title: value.title, description: value.description, category: value.category }); if (warning) ctx.addIssue({ code: z.ZodIssueCode.custom, message: warning, path: ["title"] }); } });
export const employerGigListSchema = z.object({ status: z.enum(employerGigStatusValues).optional() });
export const employerGigActionSchema = z.object({ gigId: z.string().uuid() });
export const employerApplicationReviewSchema = z.object({ applicationId: z.string().uuid(), decision: z.enum(["accepted", "rejected"]) });
export const employerBusinessProfileSchema = z.object({ fullName: z.string().trim().min(2).max(120), phone: z.string().trim().regex(/^\+[1-9]\d{7,31}$/).optional().nullable(), city: z.string().trim().max(120).optional().nullable(), neighborhood: z.string().trim().max(120).optional().nullable(), avatarUrl: z.string().url().max(2048).optional().nullable(), businessName: z.string().trim().min(2).max(140).optional().nullable(), businessCategory: z.enum(employerCategoryValues).optional().nullable(), businessDescription: z.string().trim().max(1600).optional().nullable() });
export const conversationStatusValues = ["active", "archived", "closed"] as const;
export const chatMessageTypeValues = ["text", "voice", "image", "system"] as const;
export const conversationIdSchema = z.object({ conversationId: z.string().uuid() });
export const conversationListSchema = z.object({ query: z.string().trim().max(120).optional().default(""), includeArchived: z.boolean().optional().default(false) });
export const conversationMessageListSchema = conversationIdSchema.extend({ limit: z.number().int().min(1).max(100).default(50), before: z.string().datetime().optional() });
export const chatTextMessageSchema = conversationIdSchema.extend({ content: z.string().trim().min(1, "اكتب رسالة قبل الإرسال.").max(4000, "الرسالة طويلة جداً.") });
export const chatMediaMessageSchema = conversationIdSchema.extend({ dataUrl: z.string().min(32).max(11_200_000), mimeType: z.enum(["image/jpeg", "image/png", "image/webp", "image/avif", "audio/webm", "audio/ogg", "audio/mpeg", "audio/wav"]), fileName: z.string().trim().min(1).max(120), durationMs: z.number().int().min(0).max(30_000).nullable().optional() });
export const conversationMemberActionSchema = conversationIdSchema.extend({ archived: z.boolean().optional(), hidden: z.boolean().optional() }).refine(value => value.archived !== undefined || value.hidden !== undefined, { message: "حدد الإجراء المطلوب للمحادثة." });
export const conversationCloseSchema = conversationIdSchema;
export const conversationReportSchema = z.object({ conversationId: z.string().uuid().optional(), messageId: z.string().uuid().optional(), reason: z.string().trim().min(4).max(1500) }).refine(value => Boolean(value.conversationId || value.messageId), { message: "حدد المحادثة أو الرسالة المراد الإبلاغ عنها." });
