import React, { useMemo, useState } from "react";
import { BellRing, BriefcaseBusiness, CheckCircle2, Clock3, UserPlus, XCircle } from "lucide-react";
import type { EmployerNotification } from "@shared/brikouli.types";
import { Link } from "wouter";
import { EmployerAccessState, EmployerShell } from "@/components/employer/EmployerShell";
import { JobSeekerCardSkeleton, JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { trpc } from "@/lib/trpc";
const icons: Record<EmployerNotification["type"], typeof BellRing> = { new_applicant: UserPlus, gig_date_soon: Clock3, accepted_application: CheckCircle2, rejected_application: XCircle };
export function groupEmployerNotifications(items: EmployerNotification[], todayKey: string) { return { today: items.filter(item => item.createdAt.slice(0, 10) === todayKey), earlier: items.filter(item => item.createdAt.slice(0, 10) !== todayKey) }; }

export default function EmployerNotifications() { const { isAuthenticated, loading } = useSupabaseSession(); const notifications = trpc.brikouli.employer.notifications.useQuery(undefined, { enabled: isAuthenticated }); const [read, setRead] = useState<Set<string>>(() => new Set()); const groups = useMemo(() => groupEmployerNotifications(notifications.data?.success ? notifications.data.data : [], new Date().toISOString().slice(0, 10)), [notifications.data]); if (loading) return <div className="employer-loading"><JobSeekerCardSkeleton /></div>; if (!isAuthenticated) return <EmployerAccessState type="login" />; return <EmployerShell title="تحديثات النشاط" subtitle="ملخص غير فوري مبني على طلباتك ومواعيد فرصك الفعلية.">{notifications.isLoading ? <div className="employer-loading"><JobSeekerCardSkeleton /></div> : notifications.isError || !notifications.data?.success ? <JobSeekerLoadError onRetry={() => void notifications.refetch()} /> : groups.today.length + groups.earlier.length === 0 ? <JobSeekerFeedback icon={<BellRing size={28}/>} title="لا توجد تحديثات حالياً" description="ستظهر طلبات المتقدمين ومواعيد الفرص القريبة هنا عند توفرها." /> : <><button type="button" className="employer-mark-read" onClick={() => setRead(new Set([...groups.today, ...groups.earlier].map(item => item.id)))}>تعليم الكل كمقروء</button><section className="employer-notification-group"><h2>اليوم</h2><NotificationItems items={groups.today} read={read} setRead={setRead}/></section><section className="employer-notification-group"><h2>سابقاً</h2><NotificationItems items={groups.earlier} read={read} setRead={setRead}/></section></>}</EmployerShell>; }
function NotificationItems({ items, read, setRead }: { items: EmployerNotification[]; read: Set<string>; setRead: (value: Set<string>) => void }) { if (!items.length) return <p className="employer-notification-empty">لا توجد تحديثات في هذه المجموعة.</p>; return <div className="employer-notification-list">{items.map(item => { const Icon = icons[item.type]; return <Link key={item.id} href={item.href} className={`employer-notification-card ${read.has(item.id) ? "is-read" : ""}`} onClick={() => setRead(new Set([...Array.from(read), item.id]))}><span><Icon size={19}/></span><div><b>{item.title}</b><p>{item.description}</p></div>{!read.has(item.id) && <i aria-label="غير مقروء"/>}</Link>; })}</div>; }
