import { useState } from "react";
import { Grid2X2, List, SlidersHorizontal } from "lucide-react";
import { toast } from "sonner";
import { categories, phase3Jobs } from "@/lib/phase3-data";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { BottomSheet } from "@/components/phase3/BottomSheet";
import { EmptyState } from "@/components/phase3/EmptyState";
import { PhaseJobCard } from "@/components/phase3/JobCard";
import { SearchField } from "@/components/phase3/SearchField";
export default function Explore() { const [query, setQuery] = useState(""); const [sheet, setSheet] = useState(false); const [mode, setMode] = useState<"grid" | "list">("grid"); const [selected, setSelected] = useState("الكل"); return <AppShell><section className="explore-intro"><PageHeading eyebrow="استكشف" title="فرص على مقاس يومك" action={<button className="icon-surface" onClick={() => setSheet(true)} aria-label="فتح عوامل التصفية"><SlidersHorizontal size={19} /></button>} /><SearchField value={query} onChange={setQuery} onFilter={() => setSheet(true)} placeholder="ابحث حسب المهمة أو الفئة" /><div className="filter-row" role="list">{["الكل", ...categories].map(item => <button key={item} className={selected === item ? "is-selected" : ""} onClick={() => setSelected(item)}>{item}</button>)}</div><div className="explore-tools"><span>واجهة عرض جاهزة للتمرير المستمر</span><div><button aria-label="عرض شبكي" className={mode === "grid" ? "is-active" : ""} onClick={() => setMode("grid")}><Grid2X2 size={18} /></button><button aria-label="عرض قائمة" className={mode === "list" ? "is-active" : ""} onClick={() => setMode("list")}><List size={18} /></button><button onClick={() => toast.info("سيُضاف ترتيب النتائج مع البيانات الحقيقية")}>ترتيب</button></div></div></section><section className={`explore-list explore-list-${mode}`}>{phase3Jobs.map(job => <PhaseJobCard job={job} key={job.id} />)}</section><div className="infinite-anchor"><span /> جارٍ تجهيز مزيد من الفرص <span /></div><section className="explore-empty-demo"><EmptyState title="لا توجد فرص مطابقة بعد" description="هذه حالة واجهة جاهزة عندما لا تعثر عوامل التصفية على نتائج." /></section><BottomSheet open={sheet} onClose={() => setSheet(false)} title="تصفية الفرص"><div className="sheet-content"><p>اختر فئة أو اتركها كلها لاستكشاف أوسع.</p><div className="sheet-chip-grid">{categories.map(category => <button key={category} onClick={() => { setSelected(category); setSheet(false); }}>{category}</button>)}</div><button className="app-button app-button-primary" onClick={() => { setSheet(false); toast.success("تم حفظ اختيارات الواجهة") }}>عرض النتائج</button></div></BottomSheet></AppShell>; }
