import { useState } from "react";
import { ArrowLeft, MapPinned, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from "wouter";
import { toast } from "sonner";
import { categories, phase3Jobs } from "@/lib/phase3-data";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { PhaseJobCard, JobCardSkeleton } from "@/components/phase3/JobCard";
import { SearchField } from "@/components/phase3/SearchField";
export default function Home() { const [search, setSearch] = useState(""); return <AppShell><section className="home-welcome"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .28 }}><p className="welcome-eyebrow"><MapPinned size={15} /> الفرص القريبة تبدأ من هنا</p><h1>أهلاً بك في <em>بريكولي</em></h1><p>اختَر مهمة مناسبة لوقتك، في حيّك وبشكل واضح.</p></motion.div><SearchField value={search} onChange={setSearch} onFilter={() => toast.info(search ? `استكشاف واجهة البحث عن: ${search}` : "اكتب ما تريد البحث عنه أولاً")} /><Link href="/explore" className="home-explore-cta">استكشف الفرص <ArrowLeft size={17} /></Link></section><section className="phase-section notebook-section"><PageHeading eyebrow="اختصارات سريعة" title="ماذا تريد أن تفعل اليوم؟" /><div className="category-rail">{categories.map((category, index) => <button type="button" key={category} className="category-card" onClick={() => toast.info(`فئة ${category} ستكون جاهزة للفلترة قريباً`)}><span>{String(index + 1).padStart(2, "0")}</span><b>{category}</b></button>)}</div></section><section className="phase-section"><PageHeading eyebrow="تابع من حيث توقفت" title="فرص قد تناسبك" action={<Link className="section-link" href="/explore">عرض الكل <ArrowLeft size={15} /></Link>} /><div className="home-job-grid">{phase3Jobs.slice(0, 2).map(job => <PhaseJobCard job={job} key={job.id} />)}</div></section><section className="nearby-banner"><div><p><Sparkles size={15} /> قريب منك</p><h2>فرص محلية، بخطوات أبسط.</h2><span>المسافة المعروضة هنا هي واجهة مؤقتة حتى مرحلة الخرائط.</span></div><button type="button" onClick={() => toast.info("سيتم ربط الموقع في مرحلة لاحقة")}>استكشف القريب <MapPinned size={17} /></button></section><section className="phase-section"><PageHeading eyebrow="آخر الإضافات" title="مهام حديثة" /><div className="recent-scroll">{phase3Jobs.map(job => <PhaseJobCard compact job={job} key={job.id} />)}</div></section><section className="phase-section skeleton-preview"><PageHeading eyebrow="حالة تحميل" title="جارٍ جلب فرص إضافية" /><div className="home-job-grid"><JobCardSkeleton /><JobCardSkeleton /></div></section></AppShell>; }
