import React, { useMemo, useState } from "react";
import { Archive, ChevronLeft, MessageCircle, Search, UserRound } from "lucide-react";
import { Link } from "wouter";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { JobSeekerCardSkeleton, JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { useInboxRealtime } from "@/hooks/useMessagingRealtime";
import { trpc } from "@/lib/trpc";
const preview = (item: any) => item.lastMessage?.type === "image" ? "صورة" : item.lastMessage?.type === "voice" ? "رسالة صوتية" : item.lastMessage?.content ?? "تم إنشاء المحادثة.";
const when = (iso: string) => new Date(iso).toLocaleDateString("ar-MA", { month: "short", day: "numeric" });

export default function Messages() { const { isAuthenticated, loading } = useSupabaseSession(); const [query, setQuery] = useState(""); const [archived, setArchived] = useState(false); const conversations = trpc.brikouli.messaging.list.useQuery({ query, includeArchived: archived }, { enabled: isAuthenticated }); const memberState = trpc.brikouli.messaging.memberState.useMutation(); const utils = trpc.useUtils(); useInboxRealtime(isAuthenticated, () => void utils.brikouli.messaging.list.invalidate()); const items = conversations.data?.success ? conversations.data.data : []; const hide = (id: string) => memberState.mutate({ conversationId: id, hidden: true }, { onSuccess: result => { if (result.success) void utils.brikouli.messaging.list.invalidate(); } }); if (loading || conversations.isLoading) return <AppShell><div className="chat-loading"><JobSeekerCardSkeleton/></div></AppShell>; if (!isAuthenticated) return <AppShell><section className="messages-page"><PageHeading eyebrow="الرسائل" title="مساحة التواصل"/><JobSeekerFeedback icon={<MessageCircle size={28}/>} title="سجّل الدخول لعرض المحادثات" description="تتوفر المحادثة فقط بعد قبول صاحب العمل للطلب." action={<Link href="/login" className="app-button app-button-primary">تسجيل الدخول</Link>}/></section></AppShell>; if (conversations.isError || !conversations.data?.success) return <AppShell><JobSeekerLoadError onRetry={() => void conversations.refetch()}/></AppShell>; return <AppShell><section className="messages-page"><PageHeading eyebrow="الرسائل" title="مساحة التواصل" action={<button type="button" className={`messages-archive-toggle ${archived ? "is-active" : ""}`} onClick={() => setArchived(value => !value)}><Archive size={16}/>{archived ? "الكل" : "المؤرشفة"}</button>}/><div className="messages-search"><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث بالاسم أو عنوان الفرصة" aria-label="البحث في المحادثات"/></div>{items.length === 0 ? <JobSeekerFeedback icon={<MessageCircle size={28}/>} title={archived ? "لا توجد محادثات مؤرشفة" : "لا توجد محادثات بعد"} description="تُنشأ المحادثة تلقائياً وآمناً بعد قبول طلبك في فرصة محلية."/> : <div className="conversation-list">{items.map(item => <article key={item.id} className="conversation-row"><Link href={`/messages/${item.id}`} className="conversation-main"><span className="conversation-avatar">{item.peer.avatarUrl ? <img src={item.peer.avatarUrl} alt=""/> : item.peer.fullName.slice(0, 1)}</span><span className="conversation-copy"><b>{item.peer.fullName}</b><small>{item.gigTitle}</small><p>{preview(item)}</p></span><span className="conversation-meta"><time>{when(item.updatedAt)}</time>{item.unreadCount > 0 && <i>{item.unreadCount > 99 ? "99+" : item.unreadCount}</i>}</span><ChevronLeft size={18}/></Link><button type="button" className="conversation-hide" aria-label="إخفاء المحادثة محلياً" onClick={() => hide(item.id)}>إخفاء</button></article>)}</div>}</section></AppShell>; }
