import React, { useEffect, useMemo } from "react";
import { Bell, CheckCircle2, Clock3, MessageCircle, ShieldAlert, Star, UserPlus } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { JobSeekerCardSkeleton, JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import type { NotificationItem } from "@shared/brikouli.types";

export type LegacyNotice = { id: string; title: string; description: string; createdAt: string; status: "pending" | "accepted" | "rejected"; href: string };
export type Notice = LegacyNotice;
export function buildApplicationNotices(applications: Array<{ id: string; status: "pending" | "accepted" | "rejected"; createdAt: string; gig: { title: string; employerName: string } | null }>): LegacyNotice[] { return applications.map(application => ({ id: application.id, title: application.status === "accepted" ? "تم قبول طلبك" : application.status === "rejected" ? "يوجد تحديث على طلبك" : "طلبك قيد المراجعة", description: application.gig ? `${application.gig.title} · ${application.gig.employerName}` : "فرصة محلية", createdAt: application.createdAt, status: application.status, href: "/applications" })); }
export function groupNotices(notices: LegacyNotice[], now = new Date()) { return notices.reduce<{ today: LegacyNotice[]; earlier: LegacyNotice[] }>((groups, notice) => { const date = new Date(notice.createdAt); (date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth() && date.getDate() === now.getDate() ? groups.today : groups.earlier).push(notice); return groups; }, { today: [], earlier: [] }); }
export function markNoticesRead(current: Set<string>, ids: string[]) { return new Set([...Array.from(current), ...ids]); }
export function groupNotifications(items: NotificationItem[], now = new Date()) { return items.reduce<{ today: NotificationItem[]; earlier: NotificationItem[] }>((groups, item) => { const date = new Date(item.createdAt); (date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth() && date.getDate() === now.getDate() ? groups.today : groups.earlier).push(item); return groups; }, { today: [], earlier: [] }); }
function NotificationIcon({ type }: { type: NotificationItem["type"] }) { const Icon = type === "new_message" ? MessageCircle : type === "rating_received" ? Star : type === "safety_warning" ? ShieldAlert : type === "new_applicant" ? UserPlus : type === "application_accepted" ? CheckCircle2 : Clock3; return <Icon size={18} />; }
export function NotificationCards({ items, readIds, onRead }: { items: LegacyNotice[]; readIds: Set<string>; onRead: (id: string) => void }) { return <div className="notification-list">{items.map(item => <Link href={item.href} className={`notification-card ${readIds.has(item.id) ? "is-read" : ""}`} key={item.id} onClick={() => onRead(item.id)}><span className={`notification-icon is-${item.status}`}><NotificationIcon type={item.status === "accepted" ? "application_accepted" : item.status === "rejected" ? "application_rejected" : "nearby_gig"} /></span><div><b>{item.title}</b><p>{item.description}</p></div>{!readIds.has(item.id) && <i aria-label="غير مقروء" />}</Link>)}</div>; }
function PersistedNotificationCards({ items, onRead }: { items: NotificationItem[]; onRead: (id: string) => void }) { return <div className="notification-list">{items.map(item => <Link href={item.href ?? "/notifications"} className={`notification-card ${item.read ? "is-read" : ""}`} key={item.id} onClick={() => !item.read && onRead(item.id)}><span className={`notification-icon is-${item.type}`}><NotificationIcon type={item.type} /></span><div><b>{item.title}</b><p>{item.message}</p></div>{!item.read && <i aria-label="غير مقروء" />}</Link>)}</div>; }

export default function Notifications() {
  const { isAuthenticated, user } = useSupabaseSession(); const utils = trpc.useUtils();
  const notifications = trpc.brikouli.notifications.list.useQuery({ limit: 60, unreadOnly: false }, { enabled: isAuthenticated, staleTime: 15_000 });
  const markRead = trpc.brikouli.notifications.markRead.useMutation({ onSuccess: () => void utils.brikouli.notifications.list.invalidate() });
  const items = useMemo(() => notifications.data?.success ? notifications.data.data : [], [notifications.data]); const { today, earlier } = groupNotifications(items);
  useEffect(() => { if (!user) return; const client = getSupabaseBrowserClient(); const channel = client.channel(`phase10-notifications-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "notifications", filter: `user_id=eq.${user.id}` }, () => void utils.brikouli.notifications.list.invalidate()).subscribe(); return () => { void client.removeChannel(channel); }; }, [user, utils]);
  return <AppShell><main className="jobseeker-page"><PageHeading eyebrow="متابعة النشاط" title="الإشعارات" action={items.some(item => !item.read) ? <button type="button" className="mark-all-read" onClick={() => markRead.mutate({ all: true, notificationIds: [] })} disabled={markRead.isPending}>تعليم الكل كمقروء</button> : undefined} /><p className="jobseeker-page-intro">تظهر هنا تحديثات الرسائل والطلبات والتقييمات المحفوظة في حسابك بشكل آمن.</p>{!isAuthenticated ? <JobSeekerFeedback icon={<Bell size={28} />} title="سجّل الدخول لرؤية تحديثاتك" description="ستظهر هنا الحالات المرتبطة بحسابك بعد تسجيل الدخول." action={<Link className="app-button app-button-primary" href="/login">تسجيل الدخول</Link>} /> : notifications.isLoading ? <div className="jobseeker-page-list"><JobSeekerCardSkeleton /><JobSeekerCardSkeleton /></div> : notifications.isError || (notifications.data && !notifications.data.success) ? <JobSeekerLoadError onRetry={() => void notifications.refetch()} /> : !items.length ? <JobSeekerFeedback icon={<Bell size={28} />} title="لا توجد تحديثات بعد" description="عند وصول رسالة أو تغيّر حالة طلبك، ستظهر التحديثات هنا." action={<Link className="app-button app-button-primary" href="/explore">استكشف الفرص</Link>} /> : <>{today.length > 0 && <section className="notification-group"><h2>اليوم</h2><PersistedNotificationCards items={today} onRead={id => markRead.mutate({ all: false, notificationIds: [id] })} /></section>}{earlier.length > 0 && <section className="notification-group"><h2>سابقاً</h2><PersistedNotificationCards items={earlier} onRead={id => markRead.mutate({ all: false, notificationIds: [id] })} /></section>}</>}</main></AppShell>;
}
