import { useState } from "react";
import { Link } from "wouter";
import { Star, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import type { CompletionRatingTarget } from "@shared/brikouli.types";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { JobSeekerCardSkeleton, JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import { RatingSheet } from "@/components/trust/RatingSheet";
import { SafetyNotice } from "@/components/trust/SafetyNotice";

export default function Ratings() { const { isAuthenticated } = useSupabaseSession(); const targets = trpc.brikouli.trust.ratingTargets.useQuery({ limit: 12 }, { enabled: isAuthenticated }); const utils = trpc.useUtils(); const [target, setTarget] = useState<CompletionRatingTarget | null>(null); if (!isAuthenticated) return <AppShell><main className="trust-page"><JobSeekerFeedback icon={<ShieldCheck size={28}/>} title="سجّل الدخول لمشاركة التقييمات" description="يمكنك تقييم تجربة حقيقية بعد إكمال المهمة فقط." action={<Link href="/login" className="app-button app-button-primary">تسجيل الدخول</Link>}/></main></AppShell>; if (targets.isLoading) return <AppShell><main className="trust-page"><JobSeekerCardSkeleton/><JobSeekerCardSkeleton/></main></AppShell>; if (!targets.data?.success) return <AppShell><main className="trust-page"><JobSeekerLoadError onRetry={() => void targets.refetch()}/></main></AppShell>; return <AppShell><><main className="trust-page"><PageHeading eyebrow="الثقة والتقييمات" title="شارك تجربتك"/><p className="trust-page-intro">التقييم متاح فقط بين طرفي مهمة مكتملة، ويُحتسب تلقائياً في ملف المستلم.</p><SafetyNotice compact/>{targets.data.data.length === 0 ? <JobSeekerFeedback icon={<Star size={28}/>} title="لا توجد تقييمات مطلوبة" description="عند اكتمال مهمة بينك وبين الطرف الآخر ستظهر هنا فرصة التقييم."/> : <div className="rating-target-list">{targets.data.data.map(item => <article key={item.gigId}><span>{item.target.avatarUrl ? <img src={item.target.avatarUrl} alt=""/> : item.target.fullName.slice(0,1)}</span><div><small>{item.gigTitle}</small><h2>{item.target.fullName}</h2><p>{item.submitted ? "تم إرسال تقييمك لهذه المهمة." : "تجربة مكتملة بانتظار تقييمك."}</p></div><button type="button" className="app-button app-button-primary" disabled={item.submitted} onClick={() => setTarget(item)}>{item.submitted ? "تم التقييم" : "قيّم الآن"}</button></article>)}</div>}</main><RatingSheet target={target} onClose={() => setTarget(null)} onSubmitted={() => { void targets.refetch(); void utils.brikouli.trust.profile.invalidate(); }}/></></AppShell>; }
