import { Ban, FileWarning, ShieldCheck, Unlock } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { JobSeekerCardSkeleton, JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import { SafetyNotice } from "@/components/trust/SafetyNotice";

const reportLabels: Record<string, string> = { unsafe_content: "محتوى غير آمن", scam: "احتيال أو نصب", harassment: "مضايقة", misleading: "معلومات مضللة", dangerous_work: "عمل خطير", inappropriate: "محتوى غير مناسب", other: "أخرى" };
export default function SafetySettings() { const { isAuthenticated } = useSupabaseSession(); const blocks = trpc.brikouli.blocks.list.useQuery({ limit: 50 }, { enabled: isAuthenticated }); const reports = trpc.brikouli.reports.mine.useQuery({ limit: 20 }, { enabled: isAuthenticated }); const setBlock = trpc.brikouli.blocks.set.useMutation(); const utils = trpc.useUtils(); const unblock = (userId: string) => { if (!window.confirm("هل تريد إلغاء حظر هذا الحساب؟")) return; setBlock.mutate({ userId, blocked: false }, { onSuccess: result => { if (!result.success) return toast.error(result.message); toast.success("تم إلغاء الحظر."); void utils.brikouli.blocks.list.invalidate(); } }); }; if (!isAuthenticated) return <AppShell><main className="trust-page"><JobSeekerFeedback icon={<ShieldCheck size={28}/>} title="سجّل الدخول لإدارة السلامة" description="ستظهر هنا الحسابات المحظورة وبلاغاتك الخاصة فقط." action={<Link href="/login" className="app-button app-button-primary">تسجيل الدخول</Link>}/></main></AppShell>; if (blocks.isLoading || reports.isLoading) return <AppShell><main className="trust-page"><JobSeekerCardSkeleton/></main></AppShell>; if (!blocks.data?.success || !reports.data?.success) return <AppShell><main className="trust-page"><JobSeekerLoadError onRetry={() => { void blocks.refetch(); void reports.refetch(); }}/></main></AppShell>; return <AppShell><main className="trust-page"><PageHeading eyebrow="الأمان والخصوصية" title="إدارة الأمان"/><SafetyNotice/><section className="safety-section"><header><Ban size={20}/><div><h2>الحسابات المحظورة</h2><p>الحظر يمنع الرسائل والتفاعلات الجديدة بين الحسابين.</p></div></header>{blocks.data.data.length ? <div className="blocked-list">{blocks.data.data.map(person => <article key={person.id}><span>{person.avatarUrl ? <img src={person.avatarUrl} alt=""/> : person.fullName.slice(0,1)}</span><div><b>{person.fullName}</b><small>محظور منذ {new Date(person.blockedAt).toLocaleDateString("ar-MA")}</small></div><button type="button" onClick={() => unblock(person.id)} disabled={setBlock.isPending}><Unlock size={16}/>إلغاء الحظر</button></article>)}</div> : <p className="safety-empty">لا توجد حسابات محظورة.</p>}</section><section className="safety-section"><header><FileWarning size={20}/><div><h2>بلاغاتك</h2><p>تبقى البلاغات خاصة بحسابك ولا تظهر علناً.</p></div></header>{reports.data.data.length ? <div className="report-list">{reports.data.data.map(report => <article key={report.id}><div><b>{reportLabels[report.reason] ?? "بلاغ"}</b><small>{new Date(report.createdAt).toLocaleDateString("ar-MA")}</small></div><span>{report.status === "open" ? "قيد الانتظار" : report.status}</span></article>)}</div> : <p className="safety-empty">لم ترسل أي بلاغات.</p>}</section></main></AppShell>; }
