import { useEffect, useState } from "react";
import { Bell, Eye, Globe2, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { AppShell, PageHeading } from "@/components/phase3/AppShell";
import { JobSeekerFeedback, JobSeekerLoadError } from "@/components/jobSeeker/JobSeekerFeedback";
import type { UserPreferences } from "@shared/brikouli.types";

const defaults: UserPreferences = { skills: [], availability: "flexible", preferredLanguage: "ar", notificationsEnabled: true, profileVisibility: "members" };
export default function Settings() {
  const { isAuthenticated } = useSupabaseSession(); const utils = trpc.useUtils();
  const preferences = trpc.brikouli.settings.get.useQuery(undefined, { enabled: isAuthenticated });
  const [form, setForm] = useState<UserPreferences>(defaults); const [skillsText, setSkillsText] = useState("");
  useEffect(() => { if (preferences.data?.success) { setForm(preferences.data.data); setSkillsText(preferences.data.data.skills.join("، ")); } }, [preferences.data]);
  const update = trpc.brikouli.settings.update.useMutation({ onSuccess: response => { if (response.success) { setForm(response.data); setSkillsText(response.data.skills.join("، ")); toast.success("حُفظت إعداداتك."); void utils.brikouli.settings.get.invalidate(); } else toast.error(response.message); }, onError: () => toast.error("تعذر حفظ الإعدادات الآن.") });
  const save = () => update.mutate({ ...form, skills: skillsText.split(/[،,]/).map(value => value.trim()).filter(Boolean).slice(0, 20) });
  return <AppShell><main className="jobseeker-page phase10-settings"><PageHeading eyebrow="الحساب والتفضيلات" title="الإعدادات" /><p className="jobseeker-page-intro">تحكم في التوصيات، الإشعارات، اللغة، وخصوصية ملفك من مكان واحد.</p>{!isAuthenticated ? <JobSeekerFeedback icon={<ShieldCheck size={28} />} title="سجّل الدخول لإدارة الإعدادات" description="ستظهر تفضيلات حسابك هنا بعد تسجيل الدخول." action={<Link className="app-button app-button-primary" href="/login">تسجيل الدخول</Link>} /> : preferences.isLoading ? <div className="phase10-settings-skeleton" /> : preferences.isError || (preferences.data && !preferences.data.success) ? <JobSeekerLoadError onRetry={() => void preferences.refetch()} /> : <div className="phase10-settings-stack"><section className="phase10-settings-card"><h2><Sparkles size={18} /> التوصيات والملف</h2><label>مهاراتك <input value={skillsText} onChange={event => setSkillsText(event.target.value)} placeholder="مثال: توصيل، خدمة زبناء، تنظيم" /></label><label>التوفر <select value={form.availability} onChange={event => setForm(value => ({ ...value, availability: event.target.value as UserPreferences["availability"] }))}><option value="available">متاح</option><option value="part_time">دوام جزئي</option><option value="weekends">عطلة نهاية الأسبوع</option><option value="flexible">مرن</option><option value="unavailable">غير متاح حالياً</option></select></label></section><section className="phase10-settings-card"><h2><Bell size={18} /> الإشعارات</h2><label className="phase10-switch"><span>استقبال تحديثات الرسائل والطلبات والتقييمات</span><input type="checkbox" checked={form.notificationsEnabled} onChange={event => setForm(value => ({ ...value, notificationsEnabled: event.target.checked }))} /></label></section><section className="phase10-settings-card"><h2><Globe2 size={18} /> اللغة</h2><label>لغة الواجهة <select value={form.preferredLanguage} onChange={event => setForm(value => ({ ...value, preferredLanguage: event.target.value as UserPreferences["preferredLanguage"] }))}><option value="ar">العربية</option><option value="fr">Français</option></select></label></section><section className="phase10-settings-card"><h2><Eye size={18} /> الخصوصية</h2><label>ظهور ملفك <select value={form.profileVisibility} onChange={event => setForm(value => ({ ...value, profileVisibility: event.target.value as UserPreferences["profileVisibility"] }))}><option value="members">لأعضاء المنصة فقط</option><option value="public">عام</option></select></label><Link href="/safety" className="phase10-safety-link">إدارة المستخدمين المحظورين والخصوصية</Link></section><button type="button" className="app-button app-button-primary phase10-save" onClick={save} disabled={update.isPending}>حفظ الإعدادات</button></div>}</main></AppShell>;
}
