import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export type BrowserAuthResult = { success: true; message?: string } | { success: false; message: string };
type ActionSuccess<T> = { success: true; data: T };
type ActionFailure = { success: false; message?: string };

function messageFor(error: unknown): string { return error instanceof Error ? error.message : "حدث خطأ غير متوقع."; }
async function action<T>(path: string, payload: unknown): Promise<ActionSuccess<T> | ActionFailure> { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload), credentials: "include" }); return response.json() as Promise<ActionSuccess<T> | ActionFailure>; }
async function persist(accessToken: string, refreshToken: string) { await getSupabaseBrowserClient().auth.setSession({ access_token: accessToken, refresh_token: refreshToken }); const response = await fetch("/api/auth/session", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ accessToken }) }); if (!response.ok) throw new Error("تعذر تأمين الجلسة على الخادم."); }

export async function signInWithEmail(email: string, password: string): Promise<BrowserAuthResult> { try { const result = await action<{ accessToken: string; refreshToken: string }>("/api/auth/login", { email, password }); if (!result.success) return { success: false, message: result.message ?? "تعذر تسجيل الدخول." }; await persist(result.data.accessToken, result.data.refreshToken); return { success: true }; } catch (error) { return { success: false, message: messageFor(error) }; } }
export async function registerWithEmail(input: { fullName: string; email: string; password: string; role: "job_seeker" | "employer" }): Promise<BrowserAuthResult> { try { const result = await action<{ requiresEmailConfirmation: boolean; accessToken?: string; refreshToken?: string }>("/api/auth/register", { ...input, acceptedTerms: true }); if (!result.success) return { success: false, message: result.message ?? "تعذر إنشاء الحساب." }; if (result.data.accessToken && result.data.refreshToken) await persist(result.data.accessToken, result.data.refreshToken); return { success: true, message: result.data.requiresEmailConfirmation ? "تحقق من بريدك الإلكتروني لتأكيد الحساب." : "تم إنشاء حسابك بنجاح." }; } catch (error) { return { success: false, message: messageFor(error) }; } }
export async function sendPasswordReset(email: string): Promise<BrowserAuthResult> { try { const { error } = await getSupabaseBrowserClient().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/login` }); return error ? { success: false, message: messageFor(error) } : { success: true, message: "إذا كان البريد مسجلاً، أرسلنا رابط استعادة آمن إليه." }; } catch (error) { return { success: false, message: messageFor(error) }; } }
export async function sendPhoneOtp(phone: string): Promise<BrowserAuthResult> { try { const result = await action<null>("/api/auth/phone-otp", { phone }); return result.success ? { success: true, message: "أرسلنا رمز التحقق إلى هاتفك." } : { success: false, message: result.message ?? "تعذر إرسال الرمز." }; } catch (error) { return { success: false, message: messageFor(error) }; } }
export async function verifyPhoneOtp(phone: string, token: string): Promise<BrowserAuthResult> { try { const result = await action<{ accessToken: string; refreshToken: string }>("/api/auth/verify-otp", { phone, token }); if (!result.success) return { success: false, message: result.message ?? "الرمز غير صالح." }; await persist(result.data.accessToken, result.data.refreshToken); return { success: true }; } catch (error) { return { success: false, message: messageFor(error) }; } }
export async function signOut(): Promise<BrowserAuthResult> { try { await fetch("/api/auth/logout", { method: "POST", credentials: "include" }); const { error } = await getSupabaseBrowserClient().auth.signOut(); return error ? { success: false, message: messageFor(error) } : { success: true }; } catch (error) { return { success: false, message: messageFor(error) }; } }
