import { CheckCircle2, Eye, PauseCircle, Search, ShieldBan, Trash2 } from "lucide-react";
import { useState } from "react";
import { AdminConfirmDialog } from "@/components/admin/AdminConfirmDialog";
import { AdminShell } from "@/components/admin/AdminShell";
import { trpc } from "@/lib/trpc";
type GigAction = "approve" | "reject" | "suspend" | "remove" | "request_changes" | "block";
const actionCopy: Record<GigAction, { title: string; button: string; danger: boolean }> = { approve: { title: "اعتماد الفرصة", button: "اعتماد", danger: false }, reject: { title: "رفض الفرصة", button: "تأكيد الرفض", danger: true }, suspend: { title: "تعليق الفرصة", button: "تأكيد التعليق", danger: true }, remove: { title: "إزالة الفرصة", button: "تأكيد الإزالة", danger: true }, request_changes: { title: "طلب تعديل", button: "إرسال طلب التعديل", danger: false }, block: { title: "حظر فرصة خطرة", button: "تأكيد الحظر", danger: true } };
export function AdminGigBoard({ moderationOnly = false }: { moderationOnly?: boolean }) { const [query, setQuery] = useState(""); const [pending, setPending] = useState<{ id: string; title: string; action: GigAction } | null>(null); const utils = trpc.useUtils(); const gigs = trpc.brikouli.admin.gigs.list.useQuery({ page: 1, pageSize: 25, query, moderationRisk: moderationOnly ? "review" : undefined }); const action = trpc.brikouli.admin.gigs.moderate.useMutation({ onSuccess: () => { void utils.brikouli.admin.gigs.list.invalidate(); void utils.brikouli.admin.dashboard.invalidate(); setPending(null); } }); return <><section className="admin-toolbar"><label><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث في العنوان أو المدينة أو الفئة" aria-label="البحث عن فرصة" /></label></section><section className="admin-table-panel"><table><thead><tr><th>الفرصة</th><th>صاحب العمل</th><th>إشارة السلامة</th><th>الحالة</th><th>إجراءات موثقة</th></tr></thead><tbody>{gigs.data?.success ? gigs.data.data.items.map(gig => <tr key={gig.id}><td><b>{gig.title}</b><small>{gig.category} · {gig.city}</small></td><td>{gig.employerName}<small>{gig.applicantCount} طلبات</small></td><td><span className={`admin-risk ${gig.moderationRisk}`}>{gig.moderationRisk}</span></td><td>{gig.status}</td><td className="admin-row-actions"><button onClick={() => setPending({ id: gig.id, title: gig.title, action: "approve" })}><CheckCircle2 size={16} />اعتماد</button><button onClick={() => setPending({ id: gig.id, title: gig.title, action: "suspend" })}><PauseCircle size={16} />تعليق</button><button onClick={() => setPending({ id: gig.id, title: gig.title, action: gig.moderationRisk === "blocked" ? "block" : "reject" })} className="danger"><ShieldBan size={16} />{gig.moderationRisk === "blocked" ? "حظر" : "رفض"}</button><button onClick={() => setPending({ id: gig.id, title: gig.title, action: "remove" })} className="danger"><Trash2 size={16} />إزالة</button></td></tr>) : <tr><td colSpan={5} className="admin-table-empty">{gigs.isLoading ? "جارٍ تحميل الفرص…" : "لا توجد فرص في هذه القائمة."}</td></tr>}</tbody></table></section><AdminConfirmDialog open={Boolean(pending)} title={pending ? actionCopy[pending.action].title : ""} description={`سيُطبَّق هذا الإجراء على فرصة «${pending?.title || ""}» عبر أمر إداري موثق ولا يمكن تنفيذه من واجهة عامة.`} confirmLabel={pending ? actionCopy[pending.action].button : ""} danger={pending ? actionCopy[pending.action].danger : false} busy={action.isPending} onClose={() => setPending(null)} onConfirm={() => pending && action.mutate({ gigId: pending.id, action: pending.action })} /></>; }
export default function AdminGigs() { return <AdminShell title="مراجعة الفرص" description="إدارة المحتوى وحالة النشر ضمن ضوابط السلامة."><AdminGigBoard /></AdminShell>; }
