import React, { useState } from "react";
import { Flag } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useSupabaseSession } from "@/hooks/useSupabaseSession";
import { BottomSheet } from "@/components/phase3/BottomSheet";
import type { ReportReason, ReportTargetType } from "@shared/brikouli.types";

const reasons: Array<{ value: ReportReason; label: string }> = [{ value: "unsafe_content", label: "محتوى غير آمن" }, { value: "scam", label: "احتيال أو نصب" }, { value: "harassment", label: "مضايقة" }, { value: "misleading", label: "معلومات مضللة" }, { value: "dangerous_work", label: "عمل خطير" }, { value: "inappropriate", label: "محتوى غير مناسب" }, { value: "other", label: "أخرى" }];
export function ReportSheet({ targetType, targetId, label = "إبلاغ" }: { targetType: ReportTargetType; targetId: string; label?: string }) { const { isAuthenticated } = useSupabaseSession(); const [open, setOpen] = useState(false); const [reason, setReason] = useState<ReportReason>("unsafe_content"); const [description, setDescription] = useState(""); const report = trpc.brikouli.reports.create.useMutation({ onSuccess: result => { if (!result.success) return toast.error(result.message); toast.success("تم إرسال البلاغ بشكل خاص."); setOpen(false); setDescription(""); }, onError: () => toast.error("تعذر إرسال البلاغ الآن.") }); const trigger = () => { if (!isAuthenticated) return toast.info("سجّل الدخول لإرسال بلاغ خاص وآمن."); setOpen(true); }; return <><button type="button" className="trust-report-trigger" onClick={trigger}><Flag size={16}/>{label}</button><BottomSheet open={open} onClose={() => setOpen(false)} title="الإبلاغ عن محتوى"><form className="report-sheet-form" onSubmit={event => { event.preventDefault(); report.mutate({ targetType, targetId, reason, description: description.trim() || undefined }); }}><p>سيبقى بلاغك خاصاً بحسابك. اختر السبب الأقرب، ثم أضف وصفاً اختيارياً إذا لزم.</p><fieldset><legend>سبب البلاغ</legend>{reasons.map(item => <label key={item.value}><input type="radio" name="report-reason" value={item.value} checked={reason === item.value} onChange={() => setReason(item.value)}/><span>{item.label}</span></label>)}</fieldset><label className="report-description">وصف اختياري<textarea value={description} maxLength={1500} placeholder="اشرح ما لاحظته باختصار…" onChange={event => setDescription(event.target.value)}/></label><button className="app-button app-button-primary" disabled={report.isPending}>{report.isPending ? "جارٍ الإرسال…" : "إرسال البلاغ"}</button></form></BottomSheet></>; }
