import type { ApiResult, EmployerApplicant, EmployerBusinessProfile, EmployerDashboard, EmployerGig, EmployerNotification, Gig } from "@shared/brikouli.types";
import { employerApplicationReviewSchema, employerBusinessProfileSchema, employerGigActionSchema, employerGigCreateSchema, employerGigListSchema, employerGigUpdateSchema } from "../schemas/domain";
import { createSupabaseForAccessToken, verifyActor } from "./supabase";
import { isEmployer } from "./roles";

function mapGig(row: Record<string, unknown>): Gig { return { id: String(row.id), employerId: String(row.employer_id), title: String(row.title), description: String(row.description), category: String(row.category), city: String(row.city), neighborhood: row.neighborhood ? String(row.neighborhood) : null, latitude: row.latitude === null ? null : Number(row.latitude), longitude: row.longitude === null ? null : Number(row.longitude), payment: Number(row.payment), paymentType: String(row.payment_type) as Gig["paymentType"], duration: String(row.duration), urgent: Boolean(row.urgent), status: String(row.status) as Gig["status"], createdAt: String(row.created_at) }; }
function mapEmployerGig(row: Record<string, unknown>): EmployerGig { const applications = Array.isArray(row.applications) ? row.applications as Array<Record<string, unknown>> : []; return { ...mapGig(row), acceptanceLimit: Number(row.acceptance_limit ?? 1), isPaused: Boolean(row.is_paused), workDate: row.work_date ? String(row.work_date) : null, publishedAt: row.published_at ? String(row.published_at) : null, applicantCount: Number(applications[0]?.count ?? row.applicant_count ?? 0) }; }
function mapApplicant(row: Record<string, unknown>): EmployerApplicant { const applicant = (row.applicant ?? {}) as Record<string, unknown>; return { id: String(row.id), gigId: String(row.gig_id), status: String(row.status) as EmployerApplicant["status"], createdAt: String(row.created_at), reviewedAt: row.reviewed_at ? String(row.reviewed_at) : null, applicant: { id: String(applicant.id), fullName: String(applicant.full_name ?? "باحث عن فرصة"), avatarUrl: applicant.avatar_url ? String(applicant.avatar_url) : null, rating: Number(applicant.rating ?? 0), completedJobs: Number(applicant.completed_jobs ?? 0), city: applicant.city ? String(applicant.city) : null } }; }

async function employerClient(accessToken: string) { const actor = await verifyActor(accessToken); if (!actor.success) return actor; if (!isEmployer(actor.data)) return { success: false as const, code: "FORBIDDEN", message: "منطقة صاحب العمل متاحة لحسابات أصحاب الأعمال فقط." }; const client = createSupabaseForAccessToken(accessToken); if ("success" in client) return client; return { success: true as const, actor: actor.data, client }; }

export async function listEmployerGigs(accessToken: string, input: unknown): Promise<ApiResult<EmployerGig[]>> { const parsed = employerGigListSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "حالة الفرصة غير صالحة." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; let query = scope.client.from("gigs").select("*, applications(count)").eq("employer_id", scope.actor.profile.id).order("created_at", { ascending: false }); if (parsed.data.status) query = query.eq("status", parsed.data.status); const { data, error } = await query; if (error) return { success: false, code: "EMPLOYER_GIGS_FAILED", message: "تعذر تحميل فرصك." }; return { success: true, data: (data ?? []).map(row => mapEmployerGig(row as Record<string, unknown>)) }; }

export async function createEmployerGig(accessToken: string, input: unknown): Promise<ApiResult<EmployerGig>> { const parsed = employerGigCreateSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "بيانات الفرصة غير صالحة." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const value = parsed.data; const { data, error } = await scope.client.from("gigs").insert({ employer_id: scope.actor.profile.id, title: value.title, description: value.description, category: value.category, city: value.city, neighborhood: value.neighborhood ?? null, latitude: value.latitude, longitude: value.longitude, payment: value.payment, payment_type: value.paymentType, duration: value.duration, acceptance_limit: value.acceptanceLimit, work_date: value.workDate ?? null, urgent: false, status: value.publish ? "active" : "draft" }).select("*, applications(count)").single(); if (error || !data) return { success: false, code: error?.message === "HAZARDOUS_GIG_BLOCKED" ? "HAZARDOUS_GIG_BLOCKED" : "GIG_CREATE_FAILED", message: error?.message === "HAZARDOUS_GIG_BLOCKED" ? "لا يمكن نشر هذه المهمة لأنها تتضمن عملاً عالي الخطورة." : "تعذر إنشاء الفرصة." }; return { success: true, data: mapEmployerGig(data as Record<string, unknown>) }; }

export async function updateEmployerGig(accessToken: string, input: unknown): Promise<ApiResult<EmployerGig>> { const parsed = employerGigUpdateSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "تعديلات الفرصة غير صالحة." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const { gigId, publish, ...changes } = parsed.data; const payload: Record<string, unknown> = {}; const map: Record<string, string> = { paymentType: "payment_type", acceptanceLimit: "acceptance_limit", workDate: "work_date" }; Object.entries(changes).forEach(([key, value]) => { if (value !== undefined) payload[map[key] ?? key] = value; }); if (publish !== undefined) payload.status = publish ? "active" : "draft"; const { data, error } = await scope.client.from("gigs").update(payload).eq("id", gigId).eq("employer_id", scope.actor.profile.id).select("*, applications(count)").maybeSingle(); if (error || !data) return { success: false, code: error?.message === "HAZARDOUS_GIG_BLOCKED" ? "HAZARDOUS_GIG_BLOCKED" : "GIG_UPDATE_FAILED", message: error?.message === "HAZARDOUS_GIG_BLOCKED" ? "لا يمكن حفظ مهمة عالية الخطورة." : "تعذر تحديث الفرصة أو لا تملك صلاحيتها." }; return { success: true, data: mapEmployerGig(data as Record<string, unknown>) }; }

export async function setEmployerGigPause(accessToken: string, input: unknown, paused: boolean): Promise<ApiResult<EmployerGig>> { const parsed = employerGigActionSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "معرّف الفرصة غير صالح." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data, error } = await scope.client.from("gigs").update({ is_paused: paused }).eq("id", parsed.data.gigId).eq("employer_id", scope.actor.profile.id).eq("status", "active").select("*, applications(count)").maybeSingle(); if (error || !data) return { success: false, code: "GIG_PAUSE_FAILED", message: "لا يمكن إيقاف هذه الفرصة أو استئنافها." }; return { success: true, data: mapEmployerGig(data as Record<string, unknown>) }; }

export async function cancelEmployerGig(accessToken: string, input: unknown): Promise<ApiResult<EmployerGig>> { const parsed = employerGigActionSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "معرّف الفرصة غير صالح." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data, error } = await scope.client.from("gigs").update({ status: "cancelled", is_paused: false }).eq("id", parsed.data.gigId).eq("employer_id", scope.actor.profile.id).in("status", ["draft", "active"]).select("*, applications(count)").maybeSingle(); if (error || !data) return { success: false, code: "GIG_CANCEL_FAILED", message: "لا يمكن حذف هذه الفرصة بأمان. يمكنك إلغاء الفرص النشطة أو المسودات فقط." }; return { success: true, data: mapEmployerGig(data as Record<string, unknown>) }; }

export async function listEmployerApplicants(accessToken: string, input: unknown): Promise<ApiResult<EmployerApplicant[]>> { const parsed = employerGigActionSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "معرّف الفرصة غير صالح." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data, error } = await scope.client.from("applications").select("id, gig_id, status, created_at, reviewed_at, applicant:profiles!applications_applicant_id_fkey(id, full_name, avatar_url, rating, completed_jobs, city)").eq("gig_id", parsed.data.gigId).order("created_at", { ascending: true }); if (error) return { success: false, code: "APPLICANTS_FAILED", message: "تعذر تحميل المتقدمين." }; return { success: true, data: (data ?? []).map(row => mapApplicant(row as Record<string, unknown>)) }; }

export async function reviewEmployerApplication(accessToken: string, input: unknown): Promise<ApiResult<EmployerApplicant>> { const parsed = employerApplicationReviewSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "قرار المراجعة غير صالح." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data, error } = await scope.client.rpc("review_employer_application", { p_application_id: parsed.data.applicationId, p_decision: parsed.data.decision }).single(); if (error || !data) { const code = error?.message ?? "APPLICATION_REVIEW_FAILED"; const messages: Record<string, string> = { ACCEPTANCE_LIMIT_REACHED: "تم اختيار العدد المطلوب لهذه الفرصة بالفعل.", APPLICATION_ALREADY_REVIEWED: "تمت مراجعة هذا الطلب مسبقاً.", GIG_OWNERSHIP_REQUIRED: "لا تملك صلاحية إدارة هذا الطلب." }; return { success: false, code, message: messages[code] ?? "تعذر تحديث حالة الطلب." }; } const { data: profile } = await scope.client.from("profiles").select("id, full_name, avatar_url, rating, completed_jobs, city").eq("id", (data as Record<string, unknown>).applicant_id).maybeSingle(); return { success: true, data: mapApplicant({ ...(data as Record<string, unknown>), applicant: profile ?? {} }) }; }

export async function getEmployerBusinessProfile(accessToken: string): Promise<ApiResult<EmployerBusinessProfile>> { const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data, error } = await scope.client.from("profiles").select("*").eq("id", scope.actor.profile.id).single(); if (error || !data) return { success: false, code: "BUSINESS_PROFILE_FAILED", message: "تعذر تحميل ملف النشاط." }; return { success: true, data: { ...scope.actor.profile, businessName: data.business_name ? String(data.business_name) : null, businessCategory: data.business_category ? String(data.business_category) : null, businessDescription: data.business_description ? String(data.business_description) : null } }; }

export async function updateEmployerBusinessProfile(accessToken: string, input: unknown): Promise<ApiResult<EmployerBusinessProfile>> { const parsed = employerBusinessProfileSchema.safeParse(input); if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "بيانات النشاط غير صالحة." }; const scope = await employerClient(accessToken); if (!scope.success) return scope; const value = parsed.data; const { data, error } = await scope.client.from("profiles").update({ full_name: value.fullName, phone: value.phone ?? null, city: value.city ?? null, neighborhood: value.neighborhood ?? null, avatar_url: value.avatarUrl ?? null, business_name: value.businessName ?? null, business_category: value.businessCategory ?? null, business_description: value.businessDescription ?? null }).eq("id", scope.actor.profile.id).select("*").single(); if (error || !data) return { success: false, code: "BUSINESS_PROFILE_UPDATE_FAILED", message: "تعذر حفظ ملف النشاط." }; return { success: true, data: { ...scope.actor.profile, fullName: String(data.full_name), phone: data.phone, city: data.city, neighborhood: data.neighborhood, avatarUrl: data.avatar_url, updatedAt: String(data.updated_at), businessName: data.business_name, businessCategory: data.business_category, businessDescription: data.business_description } }; }

export async function getEmployerDashboard(accessToken: string): Promise<ApiResult<EmployerDashboard>> { const scope = await employerClient(accessToken); if (!scope.success) return scope; const { data: gigs, error: gigError } = await scope.client.from("gigs").select("id, status, created_at").eq("employer_id", scope.actor.profile.id); if (gigError) return { success: false, code: "DASHBOARD_FAILED", message: "تعذر تحميل ملخص النشاط." }; const gigRows = (gigs ?? []) as Array<Record<string, unknown>>; const ids = gigRows.map(gig => String(gig.id)); const { data: applications, error: applicationError } = ids.length ? await scope.client.from("applications").select("id, status, created_at, gig_id").in("gig_id", ids) : { data: [], error: null }; if (applicationError) return { success: false, code: "DASHBOARD_FAILED", message: "تعذر تحميل ملخص الطلبات." }; const applicationRows = (applications ?? []) as Array<Record<string, unknown>>; const totalHires = applicationRows.filter(application => application.status === "accepted").length; const pendingApplications = applicationRows.filter(application => application.status === "pending").length; const decided = applicationRows.filter(application => application.status === "accepted" || application.status === "rejected").length; const now = new Date(); const weeklyActivity = Array.from({ length: 7 }, (_, index) => { const date = new Date(now); date.setUTCDate(now.getUTCDate() - (6 - index)); const key = date.toISOString().slice(0, 10); return { label: date.toLocaleDateString("ar-MA", { weekday: "short" }), gigs: gigRows.filter(gig => String(gig.created_at).slice(0, 10) === key).length, applications: applicationRows.filter(application => String(application.created_at).slice(0, 10) === key).length }; }); const monthlyHires = Array.from({ length: 6 }, (_, index) => { const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - (5 - index), 1)); const key = date.toISOString().slice(0, 7); return { label: date.toLocaleDateString("ar-MA", { month: "short" }), hires: applicationRows.filter(application => application.status === "accepted" && String(application.created_at).slice(0, 7) === key).length }; }); return { success: true, data: { stats: { totalGigs: gigRows.length, activeGigs: gigRows.filter(gig => gig.status === "active").length, completedGigs: gigRows.filter(gig => gig.status === "completed").length, pendingApplications, totalHires, acceptanceRate: decided ? Math.round((totalHires / decided) * 100) : 0 }, weeklyActivity, monthlyHires } }; }

export async function deleteEmployerGig(accessToken: string, input: unknown): Promise<ApiResult<{ gigId: string }>> {
  const parsed = employerGigActionSchema.safeParse(input);
  if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: "معرّف الفرصة غير صالح." };
  const scope = await employerClient(accessToken);
  if (!scope.success) return scope;
  const { data, error } = await scope.client.rpc("delete_employer_gig", { p_gig_id: parsed.data.gigId });
  if (error || !data) {
    const reason = error?.message ?? "GIG_DELETE_FAILED";
    const messages: Record<string, string> = { GIG_MUST_BE_CANCELLED_FIRST: "ألغِ الفرصة النشطة أولاً قبل حذفها.", GIG_HAS_APPLICANT_HISTORY: "لا يمكن حذف فرصة لديها سجل متقدمين حفاظاً على شفافية النشاط.", GIG_OWNERSHIP_REQUIRED: "لا تملك صلاحية حذف هذه الفرصة." };
    return { success: false, code: reason, message: messages[reason] ?? "تعذر حذف الفرصة." };
  }
  return { success: true, data: { gigId: String(data) } };
}

export async function updateEmployerBusinessProfileSecure(accessToken: string, input: unknown): Promise<ApiResult<EmployerBusinessProfile>> {
  const parsed = employerBusinessProfileSchema.safeParse(input);
  if (!parsed.success) return { success: false, code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "بيانات النشاط غير صالحة." };
  const scope = await employerClient(accessToken);
  if (!scope.success) return scope;
  const value = parsed.data;
  const { data, error } = await scope.client.rpc("update_employer_business_profile", { p_full_name: value.fullName, p_phone: value.phone ?? null, p_city: value.city ?? null, p_neighborhood: value.neighborhood ?? null, p_avatar_url: value.avatarUrl ?? null, p_business_name: value.businessName ?? null, p_business_category: value.businessCategory ?? null, p_business_description: value.businessDescription ?? null }).single();
  if (error || !data) return { success: false, code: error?.message ?? "BUSINESS_PROFILE_UPDATE_FAILED", message: "تعذر حفظ ملف النشاط." };
  const row = data as Record<string, unknown>;
  return { success: true, data: { ...scope.actor.profile, fullName: String(row.full_name), phone: row.phone ? String(row.phone) : null, city: row.city ? String(row.city) : null, neighborhood: row.neighborhood ? String(row.neighborhood) : null, avatarUrl: row.avatar_url ? String(row.avatar_url) : null, updatedAt: String(row.updated_at), businessName: row.business_name ? String(row.business_name) : null, businessCategory: row.business_category ? String(row.business_category) : null, businessDescription: row.business_description ? String(row.business_description) : null } };
}

export async function listEmployerNotifications(accessToken: string): Promise<ApiResult<EmployerNotification[]>> {
  const scope = await employerClient(accessToken);
  if (!scope.success) return scope;
  const { data: gigs, error: gigError } = await scope.client.from("gigs").select("id, title, status, work_date, created_at").eq("employer_id", scope.actor.profile.id).order("created_at", { ascending: false }).limit(80);
  if (gigError) return { success: false, code: "EMPLOYER_NOTIFICATIONS_FAILED", message: "تعذر تحميل تحديثات النشاط." };
  const gigRows = (gigs ?? []) as Array<Record<string, unknown>>;
  const gigById = new Map(gigRows.map(gig => [String(gig.id), gig]));
  const ids = gigRows.map(gig => String(gig.id));
  const { data: applications, error: applicationError } = ids.length ? await scope.client.from("applications").select("id, gig_id, status, created_at, applicant:profiles!applications_applicant_id_fkey(full_name)").in("gig_id", ids).order("created_at", { ascending: false }).limit(100) : { data: [], error: null };
  if (applicationError) return { success: false, code: "EMPLOYER_NOTIFICATIONS_FAILED", message: "تعذر تحميل تحديثات الطلبات." };
  const applicationNotifications = ((applications ?? []) as Array<Record<string, unknown>>).map(application => { const gig = gigById.get(String(application.gig_id)); const applicant = (application.applicant ?? {}) as Record<string, unknown>; const status = String(application.status); const type: EmployerNotification["type"] = status === "pending" ? "new_applicant" : status === "accepted" ? "accepted_application" : "rejected_application"; const descriptions: Record<EmployerNotification["type"], string> = { new_applicant: `${String(applicant.full_name ?? "باحث عن فرصة")} تقدّم إلى «${String(gig?.title ?? "فرصتك")}».`, accepted_application: `تم تأكيد قبول متقدم في «${String(gig?.title ?? "فرصتك")}».`, rejected_application: `تم إغلاق طلب في «${String(gig?.title ?? "فرصتك")}».`, gig_date_soon: "" }; return { id: `application-${String(application.id)}`, type, title: type === "new_applicant" ? "متقدم جديد" : type === "accepted_application" ? "تم قبول متقدم" : "تم رفض طلب", description: descriptions[type], createdAt: String(application.created_at), href: `/employer/gigs/${String(application.gig_id)}/applicants` }; });
  const tomorrow = new Date(); tomorrow.setUTCDate(tomorrow.getUTCDate() + 1); const soonKey = tomorrow.toISOString().slice(0, 10);
  const dateNotifications = gigRows.filter(gig => String(gig.status) === "active" && String(gig.work_date ?? "") === soonKey).map(gig => ({ id: `date-${String(gig.id)}`, type: "gig_date_soon" as const, title: "موعد مهمة قريب", description: `موعد «${String(gig.title)}» غداً. راجع التفاصيل والمتقدمين قبل الموعد.`, createdAt: String(gig.created_at), href: `/employer/gigs/${String(gig.id)}/applicants` }));
  return { success: true, data: [...applicationNotifications, ...dateNotifications].sort((a, b) => b.createdAt.localeCompare(a.createdAt)) };
}
