import type { ApiResult, BlockedUser, CompletionRatingTarget, SafetyModerationResult, TrustBadge, TrustProfile, UserReview } from "@shared/brikouli.types";
import { blockedUserListSchema, completionRatingListSchema, gigCompletionSchema, gigModerationPreviewSchema, ratingCreateSchema, reportCreateSchema, reportListSchema, trustProfileSchema, userBlockSchema } from "../schemas/domain";
import { createPublicSupabase, createSupabaseForAccessToken, verifyActor } from "./supabase";
import { isEmployer } from "./roles";
import { z } from "zod";

function fail<T>(code: string, message: string): ApiResult<T> { return { success: false, code, message }; }
function rpcFailure<T>(message: string | undefined, fallback: string): ApiResult<T> { const code = message ?? "TRUST_ACTION_FAILED"; const labels: Record<string, string> = { RATING_NOT_ALLOWED: "لا يمكنك تقييم هذه المهمة.", RATING_ALREADY_SUBMITTED: "لقد أرسلت تقييماً لهذه المهمة مسبقاً.", RATING_STARS_INVALID: "اختر تقييماً من نجمة إلى خمس نجوم.", REPORT_ALREADY_SUBMITTED: "لقد قمت بالإبلاغ عن هذا المحتوى مسبقاً.", REPORT_TARGET_NOT_AVAILABLE: "هذا المحتوى غير متاح للإبلاغ من حسابك.", CANNOT_BLOCK_SELF: "لا يمكنك حظر حسابك.", GIG_NOT_ASSIGNED: "لا يمكن إكمال فرصة غير مسندة.", ACCEPTED_APPLICATION_REQUIRED: "يلزم وجود طلب مقبول لإكمال الفرصة.", GIG_OWNER_REQUIRED: "هذا الإجراء متاح لصاحب الفرصة فقط." }; return fail(code, labels[code] ?? fallback); }
async function actorScope(accessToken: string) { const actor = await verifyActor(accessToken); if (!actor.success) return actor; const client = createSupabaseForAccessToken(accessToken); if ("success" in client) return client; return { success: true as const, data: { actor: actor.data, client } }; }
function profileValue(row: Record<string, unknown>) { return { id: String(row.id), fullName: String(row.full_name ?? "مستخدم بريكولي"), avatarUrl: row.avatar_url ? String(row.avatar_url) : null, role: String(row.role ?? "job_seeker") as "job_seeker" | "employer" | "admin" }; }

export async function getTrustProfile(input: unknown): Promise<ApiResult<TrustProfile>> { const parsed = trustProfileSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "ملف الثقة غير صالح."); const client = createPublicSupabase(); if ("success" in client) return client; const { data: profile, error: profileError } = await client.from("public_profiles").select("id, completed_jobs, created_at, rating").eq("id", parsed.data.userId).maybeSingle(); if (profileError || !profile) return fail("PROFILE_NOT_FOUND", "هذا الملف غير متاح."); const { data: ratingRows, error: ratingsError } = await client.from("ratings").select("id, gig_id, from_user, stars, comment, created_at").eq("to_user", parsed.data.userId).order("created_at", { ascending: false }).limit(200); if (ratingsError) return fail("REVIEWS_LOAD_FAILED", "تعذر تحميل التقييمات."); const rows = (ratingRows ?? []) as Array<Record<string, unknown>>; const reviewerIds = Array.from(new Set(rows.map(row => String(row.from_user)))); const { data: reviewers } = reviewerIds.length ? await client.from("public_profiles").select("id, full_name, avatar_url, role").in("id", reviewerIds) : { data: [] }; const reviewerMap = new Map(((reviewers ?? []) as Array<Record<string, unknown>>).map(row => [String(row.id), row])); const count = rows.length; const average = count ? Math.round((rows.reduce((sum, row) => sum + Number(row.stars), 0) / count) * 10) / 10 : 0; const distribution = ([5, 4, 3, 2, 1] as const).map(stars => ({ stars, count: rows.filter(row => Number(row.stars) === stars).length, percentage: count ? Math.round((rows.filter(row => Number(row.stars) === stars).length / count) * 100) : 0 })); const badges: TrustBadge[] = []; const completed = Number(profile.completed_jobs ?? 0); if (completed > 0) badges.push({ id: "completed_gigs", label: "أكمل مهام", description: `أكمل ${completed} مهمة موثقة.` }); if (count >= 3 && average >= 4.5) badges.push({ id: "strong_ratings", label: "تقييمات جيدة", description: "يعتمد على تقييمات مكتملة حقيقية." }); const memberSince = String(profile.created_at); if (Date.now() - new Date(memberSince).getTime() >= 90 * 24 * 60 * 60 * 1000) badges.push({ id: "established_member", label: "عضو منذ مدة", description: "عضوية مستمرة لأكثر من 90 يوماً." }); const recentReviews: UserReview[] = rows.slice(0, parsed.data.reviewLimit).map(row => ({ id: String(row.id), gigId: String(row.gig_id), fromUser: profileValue(reviewerMap.get(String(row.from_user)) ?? { id: row.from_user }), stars: Number(row.stars), comment: row.comment ? String(row.comment) : null, createdAt: String(row.created_at) })); return { success: true, data: { userId: parsed.data.userId, averageRating: average, reviewCount: count, distribution, recentReviews, badges, completedJobs: completed, memberSince } }; }

export async function listCompletionRatingTargets(accessToken: string, input: unknown): Promise<ApiResult<CompletionRatingTarget[]>> { const parsed = completionRatingListSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "بيانات التقييم غير صالحة."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const scope = scopeResult.data; const { data, error } = await scope.client.from("applications").select("gig_id, applicant_id, gigs!inner(id, title, employer_id, status)").eq("status", "accepted").limit(100); if (error) return fail("RATING_TARGETS_FAILED", "تعذر تحميل فرص التقييم."); const participants = ((data ?? []) as Array<Record<string, unknown>>).map(row => { const gig = Array.isArray(row.gigs) ? row.gigs[0] as Record<string, unknown> : row.gigs as Record<string, unknown>; return { row, gig }; }).filter(({ gig }) => String(gig.status) === "completed" && (String(gig.employer_id) === scope.actor.profile.id || String((data ?? []).find(item => item === item)?.applicant_id ?? "") === scope.actor.profile.id)); const applicable = participants.filter(({ row, gig }) => String(gig.employer_id) === scope.actor.profile.id || String(row.applicant_id) === scope.actor.profile.id).slice(0, parsed.data.limit); const targetIds = applicable.map(({ row, gig }) => String(gig.employer_id) === scope.actor.profile.id ? String(row.applicant_id) : String(gig.employer_id)); const { data: targetProfiles } = targetIds.length ? await scope.client.from("public_profiles").select("id, full_name, avatar_url, role").in("id", targetIds) : { data: [] }; const profileMap = new Map(((targetProfiles ?? []) as Array<Record<string, unknown>>).map(row => [String(row.id), row])); const gigIds = applicable.map(({ gig }) => String(gig.id)); const { data: ownRatings } = gigIds.length ? await scope.client.from("ratings").select("gig_id").eq("from_user", scope.actor.profile.id).in("gig_id", gigIds) : { data: [] }; const submitted = new Set(((ownRatings ?? []) as Array<Record<string, unknown>>).map(row => String(row.gig_id))); return { success: true, data: applicable.map(({ row, gig }) => { const targetId = String(gig.employer_id) === scope.actor.profile.id ? String(row.applicant_id) : String(gig.employer_id); return { gigId: String(gig.id), gigTitle: String(gig.title), target: profileValue(profileMap.get(targetId) ?? { id: targetId }), submitted: submitted.has(String(gig.id)) }; }) }; }

export async function submitRating(accessToken: string, input: unknown): Promise<ApiResult<{ id: string }>> { const parsed = ratingCreateSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", parsed.error.issues[0]?.message ?? "بيانات التقييم غير صالحة."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const { data, error } = await scopeResult.data.client.rpc("submit_completion_rating", { p_gig_id: parsed.data.gigId, p_to_user: parsed.data.toUser, p_stars: parsed.data.stars, p_comment: parsed.data.comment ?? "" }); return error || !data ? rpcFailure(error?.message, "تعذر حفظ التقييم.") : { success: true, data: { id: String(data) } }; }

export async function createPrivateReport(accessToken: string, input: unknown): Promise<ApiResult<{ id: string }>> { const parsed = reportCreateSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "بيانات البلاغ غير صالحة."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const { data, error } = await scopeResult.data.client.rpc("create_private_report", { p_target_type: parsed.data.targetType, p_target_id: parsed.data.targetId, p_reason: parsed.data.reason, p_description: parsed.data.description ?? "" }); return error || !data ? rpcFailure(error?.message, "تعذر إرسال البلاغ.") : { success: true, data: { id: String(data) } }; }

export async function listMyReports(accessToken: string, input: unknown): Promise<ApiResult<Array<{ id: string; targetType: string; targetId: string; reason: string; description: string | null; status: string; createdAt: string }>>> { const parsed = reportListSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "طلب البلاغات غير صالح."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const { data, error } = await scopeResult.data.client.from("reports").select("id, target_type, target_id, reason, description, status, created_at").order("created_at", { ascending: false }).limit(parsed.data.limit); if (error) return fail("REPORTS_LOAD_FAILED", "تعذر تحميل بلاغاتك."); return { success: true, data: ((data ?? []) as Array<Record<string, unknown>>).map(row => ({ id: String(row.id), targetType: String(row.target_type), targetId: String(row.target_id), reason: String(row.reason), description: row.description ? String(row.description) : null, status: String(row.status), createdAt: String(row.created_at) })) }; }

export async function setTrustedBlock(accessToken: string, input: unknown): Promise<ApiResult<{ userId: string; blocked: boolean }>> { const parsed = userBlockSchema.extend({ blocked: z.boolean() }).safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "الحساب المحدد غير صالح."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const { error } = await scopeResult.data.client.rpc("set_private_user_block", { p_blocked_id: parsed.data.userId, p_blocked: parsed.data.blocked }); return error ? rpcFailure(error.message, "تعذر تحديث الحظر.") : { success: true, data: { userId: parsed.data.userId, blocked: parsed.data.blocked } }; }

export async function listBlockedUsers(accessToken: string, input: unknown): Promise<ApiResult<BlockedUser[]>> { const parsed = blockedUserListSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "طلب الحظر غير صالح."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; const { data, error } = await scopeResult.data.client.from("user_blocks").select("blocked_id, created_at").order("created_at", { ascending: false }).limit(parsed.data.limit); if (error) return fail("BLOCK_LIST_FAILED", "تعذر تحميل الحسابات المحظورة."); const ids = ((data ?? []) as Array<Record<string, unknown>>).map(row => String(row.blocked_id)); const { data: profiles } = ids.length ? await scopeResult.data.client.from("public_profiles").select("id, full_name, avatar_url, role").in("id", ids) : { data: [] }; const profileMap = new Map(((profiles ?? []) as Array<Record<string, unknown>>).map(row => [String(row.id), row])); return { success: true, data: ((data ?? []) as Array<Record<string, unknown>>).map(row => ({ ...profileValue(profileMap.get(String(row.blocked_id)) ?? { id: row.blocked_id }), blockedAt: String(row.created_at) })) }; }

export async function completeGigSecure(accessToken: string, input: unknown): Promise<ApiResult<{ gigId: string; status: "completed" }>> { const parsed = gigCompletionSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "معرّف الفرصة غير صالح."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; if (!isEmployer(scopeResult.data.actor)) return fail("FORBIDDEN", "إكمال الفرص متاح لصاحب العمل فقط."); const { data, error } = await scopeResult.data.client.rpc("complete_owned_gig", { p_gig_id: parsed.data.gigId }); return error || !data ? rpcFailure(error?.message, "تعذر إكمال الفرصة.") : { success: true, data: { gigId: String((data as Record<string, unknown>).id), status: "completed" } }; }

export function moderateGigPreview(input: { title: string; description: string; category: string }): SafetyModerationResult { const normalize = (value: string) => value.toLocaleLowerCase("ar").replace(/[أإآٱ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه").replace(/[^a-zA-Z0-9\u0600-\u06FF\s]/g, " ").replace(/\s+/g, " ").trim(); const content = normalize(`${input.title} ${input.description} ${input.category}`); const blocked = /(جهد عال[ي]?|كهرباء.*عال[ي]?|اسلاك مكشوفة|متفجرات|تفجير|مواد متفجرة|high voltage|live wire|explosives|هدم ثقيل|حفريات عميقة|ماكينة خطرة|منشار صناعي|heavy construction|dangerous machinery)/.test(content); if (blocked) return { allowed: false, riskLevel: "blocked", userMessage: "لا يمكن نشر هذه الفرصة حفاظاً على السلامة." }; const review = /(سقالة|ارتفاع|سطح مرتفع|تسلق|رافعة|غاز|كهرباء|اله ثقيلة|معدات ثقيلة|high altitude|scaffold|crane)/.test(content); return review ? { allowed: false, riskLevel: "review", userMessage: "تحتاج هذه الفرصة إلى مراجعة سلامة قبل النشر." } : { allowed: true, riskLevel: "safe", userMessage: null }; }
export async function getModerationPreview(accessToken: string, input: unknown): Promise<ApiResult<SafetyModerationResult>> { const parsed = gigModerationPreviewSchema.safeParse(input); if (!parsed.success) return fail("VALIDATION_ERROR", "بيانات مراجعة السلامة غير صالحة."); const scopeResult = await actorScope(accessToken); if (!scopeResult.success) return scopeResult; if (!isEmployer(scopeResult.data.actor)) return fail("FORBIDDEN", "مراجعة الفرص متاحة لأصحاب الأعمال فقط."); return { success: true, data: moderateGigPreview(parsed.data) }; }
